config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'order_details/update'
  end
  namespace :admin do
    get 'orders/show'
    get 'orders/update'
  end
  namespace :admin do
    get 'customers/index'
    get 'customers/show'
    get 'customers/edit'
    get 'customers/update'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/create'
    get 'genres/edit'
    get 'genres/update'
  end
  namespace :admin do
    get 'items/index'
    get 'items/new'
    get 'items/create'
    get 'items/show'
    get 'items/edit'
    get 'items/update'
  end
  namespace :admin do
    get 'homes/top'
  end
  namespace :public do
    get 'addresses/index'
    get 'addresses/edit'
    get 'addresses/create'
    get 'addresses/update'
    get 'addresses/destroy'
  end
  namespace :public do
    get 'orders/new'
    get 'orders/confirm'
    get 'orders/thank'
    get 'orders/create'
    get 'orders/index'
    get 'orders/show'
  end
  namespace :public do
    get 'cart_items/index'
    get 'cart_items/update'
    get 'cart_items/destroy'
    get 'cart_items/destroy_all'
    get 'cart_items/create'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :public do
    get 'homes/top'

  end
  namespace :public do
    get 'customers/my_page'
    get 'customers/edit'
    get 'customers/update'
    get 'customers/unsubscribe'
    get 'customers/withdrawal'
  end
  root to: 'public/homes#top'
  get 'public/home/about' => 'public/homes#about'
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :item_id, uniqueness: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :order_details, through: :orders

  def full_name
    first_name + last_name
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items
    has_many :order_details
    has_one_attached :image
    belongs_to :genre

    enum sales_status: { on_sale: 0, off_sale: 1 }

    def self.search(search)
        if search
            where(['name LIKE ?', "%#{search}%"])
        else
            all
        end
    end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, confirmation_of_payment: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { production_not_possible: 0, waiting_for_production: 1, in_production: 2, completion_of_production: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :genre_id, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def update
    order = Order.find(params[:id])
    if params[:order][:status] == "b"
      order.ordered_items.each do |ordered_item|
        ordered_item.production_status = "b"
        ordered_item.update(production_status: ordered_item.production_status)
      end
    end
    order.update(order_params)
    redirect_to admin_order_path(order)
  end

  def show
    @order = Order.find(params[:id])
    @ordered_item = @order.ordered_items

    @total = 0
    @ordered_item.each do |ordered_item|
      tol = ordered_item.item.non_taxed_price * ordered_item.quantity
      @total += tol
    end
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  
    case resource
      when Admin
        root_path
      when Customer
        root_path
    end
  end

  def after_sign_out_path_for(resource)
    public_home_about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<h1>Admin::Genres#edit</h1>
<p>Find me in app/views/admin/genres/edit.html.erb</p>

app/views/admin/genres/index.html.erb
<h1>Admin::Genres#index</h1>
<p>Find me in app/views/admin/genres/index.html.erb</p>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_for @item, url: admin_item_path(@item) do |f| %>

    <div class="form-group has-icon">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :image %><br />
      <%= f.attachment_field :image %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :genre_id %>
      <%= f.select :genre_id, [["ケーキ", "1"], include_blank: "選択して下さい" %>

    </div>
    <div class="form-group has-icon">
      <%= f.label :non_taxed_price %>
      <%= f.text_field :non_taxed_price, class:"form-control" %>

    </div>
    <div class="form-group has-icon">
      <%= f.radio_button :sales_status, :on_sale %>
  　　 <%= f.label :sales_status, "有効", {value: :true, style: "display: inline-block;"} %>
  　　 <%= f.radio_button :sales_status, :off_sale %>
  　　 <%= f.label :sales_status, "無効", {value: :false, style: "display: inline-block;"} %>

    </div>
    <%= f.submit "これで確定する", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
  <% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<table class="table table-striped bg-light">
<tr>
  <th>商品名</th>
  <th>商品単価</th>
  <th>販売ステータス</th>
</tr>
<% @items.each do |item| %>
  <tr>
    <td><%= link_to item.name, admin_item_path(item) %></td>
    <td><%= item.non_taxed_price %>
    <td><%= item.sales_status_i18n %></td>
  </tr>
<% end %>

app/views/admin/items/new.html.erb
<h1>商品登録</h1>
<div class="row">
<div class="col-xs-9">
<%= form_for @item, :url => {:action => :create} do |f| %>

    <div class="form-group has-icon">
      <%= f.label :name, "商品名" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :name, "商品説明" %>
      <%= f.text_area :description, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :image, "商品画像" %><br />
      <%= f.file_field :image, accept: "image/*" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :genre_id, "商品種別" %><br />
      <%= f.select :genre_id, ["ケーキ", "1"], include_blank: "選択して下さい" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :non_taxed_price, "値段(税抜き)" %>
      <%= f.text_field :non_taxed_price, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.radio_button :sales_status, :on_sale, checked: "checked"%>
       <%= f.label :sales_status, "有効", {value: :"0", style: "display: inline-block;"} %>
       <%= f.radio_button :sales_status, :off_sale %>
       <%= f.label :sales_status, "無効", {value: :"1", style: "display: inline-block;"} %>
    </div>
    <%= f.submit "この内容で登録する", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
  <% end %>
  </div>
  </div>

app/views/admin/items/show.html.erb
<h2 class="pb-2 mb-4"><%= @item.name %></h2>

<div class="row">
  <div class="col-6">
    <%= attachment_image_tag @item, :image, format: 'jpeg', fallback: "ithigo.jpg", style: "max-width: 100%"%>
  </div>
  <div class="col-6">
    <table class="table">
    <tr>
        <th>商品名</th>
        <td><%= @item.name%></td>
    </tr>
    <tr>
        <th>紹介文</th>
        <td><%= @item.description %></td>
    </tr>
    <tr>
        <th>単価</th>
        <td><%= @item.non_taxed_price %></td>
    </tr>
    <tr>
        <th>商品種別</th>
        <td><%= @item.genre.name %></td>
    </tr>
    <tr>
        <th>販売ステータス</th>
        <td><%= @item.sales_status_i18n %></td>
    </tr>
    </table>
    <%= link_to "この商品を編集する", edit_admin_item_path(@item), class: "btn btn-info"%>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/show.html.erb
<h1>受注詳細 </h1>

<div>購入者 : <%= @order.customer.full_name %></div>

<div>配送先 ：<%= @order.shipping_address %></div>

<div>支払い方法 :
<%= @order.payment_method_i18n %>
</div>

注文ステータス :
<%= form_for @order, url: admin_order_path do |f| %>
  <%= f.select :status, Order.statuses_i18n.invert %>
  <%= f.submit %>
<% end %>


<table border="1">
    <thead>
        <tr>
            <th>商品名</th>
            <th>単価</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
        </tr>
    </thead>
    <tbody>
        <% @ordered_item.each do |ordered_item| %>
            <tr>
                <td><%= ordered_item.item.name %></td>
                <td><%= ordered_item.item.non_taxed_price %></td>
                <td><%= ordered_item.quantity %></td>
                <td><%= ordered_item.item.non_taxed_price * ordered_item.quantity %></td>
                <%= form_for ordered_item, url: admin_ordered_item_path do |f| %>
                  <td><%= f.select :production_status, OrderedItem.production_statuses_i18n.invert %>
                  <%= f.hidden_field :ordered_item_id, :value => ordered_item.id %>
                  <%= f.submit '変更する' %></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

<div>商品合計 : <%= @total %></div>
<div>送料 : <%= @order.postage %></div>
<div>請求合計金額 : <%= @total + @order.postage %></div>

app/views/admin/orders/update.html.erb
<h1>受注一覧</h1>


<table border="1">
        <thead>
            <tr>
                <th>購入日時</th>
                <th>購入者</th>
                <th>注文個数</th>
                <th>注文ステータス</th>
            </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <% %>
  　　　　　<tr>
            <td><%= link_to order.created_at, admin_order_path(order) %></td>
            <td><%= order.customer.full_name %></td>
            <td><%= order.ordered_items.sum(:quantity) %></td>
            <td><%= order.status %></td>
          </tr>
　　　　　<% end %>
        </tbody>
    </table>